// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: actions_processor_llm.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActionProcessorService_ProcessActions_FullMethodName = "/ActionProcessorService/ProcessActions"
)

// ActionProcessorServiceClient is the client API for ActionProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис, обрабатывающий действия и возвращающий сгенерированный JSON
type ActionProcessorServiceClient interface {
	// RPC метод, принимающий список действий и возвращающий произвольную JSON-структуру
	ProcessActions(ctx context.Context, in *ActionList, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type actionProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActionProcessorServiceClient(cc grpc.ClientConnInterface) ActionProcessorServiceClient {
	return &actionProcessorServiceClient{cc}
}

func (c *actionProcessorServiceClient) ProcessActions(ctx context.Context, in *ActionList, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, ActionProcessorService_ProcessActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionProcessorServiceServer is the server API for ActionProcessorService service.
// All implementations must embed UnimplementedActionProcessorServiceServer
// for forward compatibility.
//
// Сервис, обрабатывающий действия и возвращающий сгенерированный JSON
type ActionProcessorServiceServer interface {
	// RPC метод, принимающий список действий и возвращающий произвольную JSON-структуру
	ProcessActions(context.Context, *ActionList) (*structpb.Struct, error)
	mustEmbedUnimplementedActionProcessorServiceServer()
}

// UnimplementedActionProcessorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActionProcessorServiceServer struct{}

func (UnimplementedActionProcessorServiceServer) ProcessActions(context.Context, *ActionList) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessActions not implemented")
}
func (UnimplementedActionProcessorServiceServer) mustEmbedUnimplementedActionProcessorServiceServer() {
}
func (UnimplementedActionProcessorServiceServer) testEmbeddedByValue() {}

// UnsafeActionProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionProcessorServiceServer will
// result in compilation errors.
type UnsafeActionProcessorServiceServer interface {
	mustEmbedUnimplementedActionProcessorServiceServer()
}

func RegisterActionProcessorServiceServer(s grpc.ServiceRegistrar, srv ActionProcessorServiceServer) {
	// If the following call pancis, it indicates UnimplementedActionProcessorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActionProcessorService_ServiceDesc, srv)
}

func _ActionProcessorService_ProcessActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionProcessorServiceServer).ProcessActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionProcessorService_ProcessActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionProcessorServiceServer).ProcessActions(ctx, req.(*ActionList))
	}
	return interceptor(ctx, in, info, handler)
}

// ActionProcessorService_ServiceDesc is the grpc.ServiceDesc for ActionProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActionProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ActionProcessorService",
	HandlerType: (*ActionProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessActions",
			Handler:    _ActionProcessorService_ProcessActions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "actions_processor_llm.proto",
}
