DROP TABLE IF EXISTS public.test;

CREATE TABLE IF NOT EXISTS public.user
(
    id BIGINT NOT NULL
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vkid TEXT NOT NULL UNIQUE
        CHECK(vkid <> ''),
    name TEXT NOT NULL
        CHECK(name <> '')
        CONSTRAINT max_len_name CHECK(LENGTH(name) < 100),
    avatar TEXT NOT NULL
        CHECK(avatar != '')
);
