CREATE TABLE IF NOT EXISTS public.encounter_store
(
    id BIGINT NOT NULL
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL
        REFERENCES public.user(id),
    name TEXT NOT NULL
        CHECK(name <> '')
        CONSTRAINT max_len_name CHECK(LENGTH(name) <= 60),
    data BYTEA NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX encounter_name_search_idx
ON public.encounter_store
USING GIN (
    (to_tsvector('russian', name) || to_tsvector('english', name))
);

CREATE INDEX encounter_user_id_idx
ON public.encounter_store (user_id);
