ALTER TABLE public.encounter_store
ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Заполняем ID для существующих строк
WITH numbered AS (
    SELECT uuid, ROW_NUMBER() OVER () AS rn
    FROM public.encounter_store
)
UPDATE public.encounter_store e
SET id = n.rn
FROM numbered n
WHERE e.uuid = n.uuid;

ALTER TABLE public.encounter_store
DROP CONSTRAINT encounter_store_pkey;

ALTER TABLE public.encounter_store
ADD PRIMARY KEY (id);

ALTER TABLE public.encounter_store
ADD CONSTRAINT encounter_store_uuid_key UNIQUE (uuid);


CREATE UNIQUE INDEX encounter_uuid_idx
ON public.encounter_store (uuid);
