CREATE TABLE IF NOT EXISTS public.user_identity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
    provider         TEXT   NOT NULL,
    provider_user_id TEXT   NOT NULL,
    email            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at     TIMESTAMPTZ,
    CONSTRAINT uq_identity_provider      UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_identity_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_identity_user_id ON public.user_identity(user_id);

-- Backfill: copy VK identities from user table (idempotent)
INSERT INTO public.user_identity (user_id, provider, provider_user_id, created_at)
SELECT id, 'vk', vkid, created_at
FROM public."user"
WHERE vkid IS NOT NULL
ON CONFLICT (provider, provider_user_id) DO NOTHING;

-- Make vkid nullable (preparation for PR5 drop)
ALTER TABLE public."user" ALTER COLUMN vkid DROP NOT NULL;
