// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_description.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDescriptionUsecases is a mock of DescriptionUsecases interface.
type MockDescriptionUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockDescriptionUsecasesMockRecorder
	isgomock struct{}
}

// MockDescriptionUsecasesMockRecorder is the mock recorder for MockDescriptionUsecases.
type MockDescriptionUsecasesMockRecorder struct {
	mock *MockDescriptionUsecases
}

// NewMockDescriptionUsecases creates a new mock instance.
func NewMockDescriptionUsecases(ctrl *gomock.Controller) *MockDescriptionUsecases {
	mock := &MockDescriptionUsecases{ctrl: ctrl}
	mock.recorder = &MockDescriptionUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescriptionUsecases) EXPECT() *MockDescriptionUsecasesMockRecorder {
	return m.recorder
}

// GenerateDescription mocks base method.
func (m *MockDescriptionUsecases) GenerateDescription(ctx context.Context, req models.DescriptionGenerationRequest) (models.DescriptionGenerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDescription", ctx, req)
	ret0, _ := ret[0].(models.DescriptionGenerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDescription indicates an expected call of GenerateDescription.
func (mr *MockDescriptionUsecasesMockRecorder) GenerateDescription(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDescription", reflect.TypeOf((*MockDescriptionUsecases)(nil).GenerateDescription), ctx, req)
}

// MockDescriptionGateway is a mock of DescriptionGateway interface.
type MockDescriptionGateway struct {
	ctrl     *gomock.Controller
	recorder *MockDescriptionGatewayMockRecorder
	isgomock struct{}
}

// MockDescriptionGatewayMockRecorder is the mock recorder for MockDescriptionGateway.
type MockDescriptionGatewayMockRecorder struct {
	mock *MockDescriptionGateway
}

// NewMockDescriptionGateway creates a new mock instance.
func NewMockDescriptionGateway(ctrl *gomock.Controller) *MockDescriptionGateway {
	mock := &MockDescriptionGateway{ctrl: ctrl}
	mock.recorder = &MockDescriptionGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescriptionGateway) EXPECT() *MockDescriptionGatewayMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockDescriptionGateway) Describe(ctx context.Context, firstCharID, secondCharID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", ctx, firstCharID, secondCharID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockDescriptionGatewayMockRecorder) Describe(ctx, firstCharID, secondCharID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockDescriptionGateway)(nil).Describe), ctx, firstCharID, secondCharID)
}
