// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_maptiles.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMapTilesRepository is a mock of MapTilesRepository interface.
type MockMapTilesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMapTilesRepositoryMockRecorder
	isgomock struct{}
}

// MockMapTilesRepositoryMockRecorder is the mock recorder for MockMapTilesRepository.
type MockMapTilesRepositoryMockRecorder struct {
	mock *MockMapTilesRepository
}

// NewMockMapTilesRepository creates a new mock instance.
func NewMockMapTilesRepository(ctrl *gomock.Controller) *MockMapTilesRepository {
	mock := &MockMapTilesRepository{ctrl: ctrl}
	mock.recorder = &MockMapTilesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapTilesRepository) EXPECT() *MockMapTilesRepositoryMockRecorder {
	return m.recorder
}

// GetCategories mocks base method.
func (m *MockMapTilesRepository) GetCategories(ctx context.Context, userID int) ([]*models.MapTileCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx, userID)
	ret0, _ := ret[0].([]*models.MapTileCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockMapTilesRepositoryMockRecorder) GetCategories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockMapTilesRepository)(nil).GetCategories), ctx, userID)
}

// MockMapTilesUsecases is a mock of MapTilesUsecases interface.
type MockMapTilesUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockMapTilesUsecasesMockRecorder
	isgomock struct{}
}

// MockMapTilesUsecasesMockRecorder is the mock recorder for MockMapTilesUsecases.
type MockMapTilesUsecasesMockRecorder struct {
	mock *MockMapTilesUsecases
}

// NewMockMapTilesUsecases creates a new mock instance.
func NewMockMapTilesUsecases(ctrl *gomock.Controller) *MockMapTilesUsecases {
	mock := &MockMapTilesUsecases{ctrl: ctrl}
	mock.recorder = &MockMapTilesUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapTilesUsecases) EXPECT() *MockMapTilesUsecasesMockRecorder {
	return m.recorder
}

// GetCategories mocks base method.
func (m *MockMapTilesUsecases) GetCategories(ctx context.Context, userID int) ([]*models.MapTileCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx, userID)
	ret0, _ := ret[0].([]*models.MapTileCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockMapTilesUsecasesMockRecorder) GetCategories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockMapTilesUsecases)(nil).GetCategories), ctx, userID)
}
