// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_character.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterRepository is a mock of CharacterRepository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// AddCharacter mocks base method.
func (m *MockCharacterRepository) AddCharacter(ctx context.Context, rawChar models.CharacterRaw, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCharacter", ctx, rawChar, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCharacter indicates an expected call of AddCharacter.
func (mr *MockCharacterRepositoryMockRecorder) AddCharacter(ctx, rawChar, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCharacter", reflect.TypeOf((*MockCharacterRepository)(nil).AddCharacter), ctx, rawChar, userID)
}

// GetCharacterByMongoId mocks base method.
func (m *MockCharacterRepository) GetCharacterByMongoId(ctx context.Context, id string) (*models.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByMongoId", ctx, id)
	ret0, _ := ret[0].(*models.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByMongoId indicates an expected call of GetCharacterByMongoId.
func (mr *MockCharacterRepositoryMockRecorder) GetCharacterByMongoId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByMongoId", reflect.TypeOf((*MockCharacterRepository)(nil).GetCharacterByMongoId), ctx, id)
}

// GetCharactersList mocks base method.
func (m *MockCharacterRepository) GetCharactersList(ctx context.Context, size, start, userID int, search models.SearchParams) ([]*models.CharacterShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharactersList", ctx, size, start, userID, search)
	ret0, _ := ret[0].([]*models.CharacterShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharactersList indicates an expected call of GetCharactersList.
func (mr *MockCharacterRepositoryMockRecorder) GetCharactersList(ctx, size, start, userID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharactersList", reflect.TypeOf((*MockCharacterRepository)(nil).GetCharactersList), ctx, size, start, userID, search)
}

// MockCharacterUsecases is a mock of CharacterUsecases interface.
type MockCharacterUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterUsecasesMockRecorder
	isgomock struct{}
}

// MockCharacterUsecasesMockRecorder is the mock recorder for MockCharacterUsecases.
type MockCharacterUsecasesMockRecorder struct {
	mock *MockCharacterUsecases
}

// NewMockCharacterUsecases creates a new mock instance.
func NewMockCharacterUsecases(ctrl *gomock.Controller) *MockCharacterUsecases {
	mock := &MockCharacterUsecases{ctrl: ctrl}
	mock.recorder = &MockCharacterUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterUsecases) EXPECT() *MockCharacterUsecasesMockRecorder {
	return m.recorder
}

// AddCharacter mocks base method.
func (m *MockCharacterUsecases) AddCharacter(ctx context.Context, file multipart.File, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCharacter", ctx, file, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCharacter indicates an expected call of AddCharacter.
func (mr *MockCharacterUsecasesMockRecorder) AddCharacter(ctx, file, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCharacter", reflect.TypeOf((*MockCharacterUsecases)(nil).AddCharacter), ctx, file, userID)
}

// GetCharacterByMongoId mocks base method.
func (m *MockCharacterUsecases) GetCharacterByMongoId(ctx context.Context, id string, userID int) (*models.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByMongoId", ctx, id, userID)
	ret0, _ := ret[0].(*models.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByMongoId indicates an expected call of GetCharacterByMongoId.
func (mr *MockCharacterUsecasesMockRecorder) GetCharacterByMongoId(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByMongoId", reflect.TypeOf((*MockCharacterUsecases)(nil).GetCharacterByMongoId), ctx, id, userID)
}

// GetCharactersList mocks base method.
func (m *MockCharacterUsecases) GetCharactersList(ctx context.Context, size, start, userID int, search models.SearchParams) ([]*models.CharacterShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharactersList", ctx, size, start, userID, search)
	ret0, _ := ret[0].([]*models.CharacterShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharactersList indicates an expected call of GetCharactersList.
func (mr *MockCharacterUsecasesMockRecorder) GetCharactersList(ctx, size, start, userID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharactersList", reflect.TypeOf((*MockCharacterUsecases)(nil).GetCharactersList), ctx, size, start, userID, search)
}
