//go:build integration
// +build integration

package repository_test

import (
	"context"
	"encoding/json"
	"os"
	"testing"

	"github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	"github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/pkg/encounter/repository"
	"github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/pkg/testhelpers"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
)

const (
	setupSQL = `
		CREATE TABLE IF NOT EXISTS public."user" (
			id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			vkid TEXT NOT NULL UNIQUE CHECK(vkid <> ''),
			name TEXT NOT NULL CHECK(name <> '') CONSTRAINT max_len_name CHECK(LENGTH(name) < 100),
			avatar TEXT NOT NULL CHECK(avatar != '')
		);

		CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

		CREATE TABLE IF NOT EXISTS public.encounter_store (
			user_id BIGINT NOT NULL REFERENCES public."user"(id),
			name TEXT NOT NULL CHECK(name <> '') CONSTRAINT max_len_name CHECK(LENGTH(name) <= 60),
			data BYTEA NOT NULL,
			is_deleted BOOLEAN DEFAULT FALSE,
			uuid UUID NOT NULL PRIMARY KEY
		);
	`

	seedUserSQL = `
		INSERT INTO public."user" (vkid, name, avatar)
		VALUES ('test-vk-001', 'Integration Tester', 'https://example.com/avatar.png')
		ON CONFLICT (vkid) DO NOTHING
		RETURNING id;
	`

	cleanupSQL = `
		DELETE FROM public.encounter_store WHERE name = 'Integration Smoke Test';
		DELETE FROM public."user" WHERE vkid = 'test-vk-001';
	`

	teardownSQL = `
		DROP TABLE IF EXISTS public.encounter_store;
		DROP TABLE IF EXISTS public."user";
	`
)

func TestEncounterRepo_SaveAndGetByID(t *testing.T) {
	dsn := os.Getenv("TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("TEST_POSTGRES_DSN not set — skipping integration test")
	}

	ctx := context.Background()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("failed to connect to postgres: %v", err)
	}
	defer pool.Close()

	if err := pool.Ping(ctx); err != nil {
		t.Fatalf("failed to ping postgres: %v", err)
	}

	// Setup schema.
	_, err = pool.Exec(ctx, setupSQL)
	if err != nil {
		t.Fatalf("failed to setup schema: %v", err)
	}
	t.Cleanup(func() {
		pool.Exec(ctx, cleanupSQL)
		pool.Exec(ctx, teardownSQL)
	})

	// Seed a test user.
	var userID int
	err = pool.QueryRow(ctx, seedUserSQL).Scan(&userID)
	if err != nil {
		t.Fatalf("failed to seed test user: %v", err)
	}

	repo := repository.NewEncounterStorage(pool, testhelpers.NoopDBMetrics())

	encounterUUID := "00000000-0000-0000-0000-000000000001"
	saveReq := &models.SaveEncounterReq{
		Name: "Integration Smoke Test",
		Data: json.RawMessage(`{"monsters":[]}`),
	}

	// Save.
	err = repo.SaveEncounter(ctx, saveReq, encounterUUID, userID)
	assert.NoError(t, err)

	// GetByID.
	got, err := repo.GetEncounterByID(ctx, encounterUUID)
	assert.NoError(t, err)

	assert.Equal(t, saveReq.Name, got.Name)
	assert.Equal(t, encounterUUID, got.UUID)
	assert.Equal(t, userID, got.UserID)
}
