// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_table.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	table "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/pkg/table"
	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockTableManager is a mock of TableManager interface.
type MockTableManager struct {
	ctrl     *gomock.Controller
	recorder *MockTableManagerMockRecorder
	isgomock struct{}
}

// MockTableManagerMockRecorder is the mock recorder for MockTableManager.
type MockTableManagerMockRecorder struct {
	mock *MockTableManager
}

// NewMockTableManager creates a new mock instance.
func NewMockTableManager(ctrl *gomock.Controller) *MockTableManager {
	mock := &MockTableManager{ctrl: ctrl}
	mock.recorder = &MockTableManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableManager) EXPECT() *MockTableManagerMockRecorder {
	return m.recorder
}

// AddNewConnection mocks base method.
func (m *MockTableManager) AddNewConnection(ctx context.Context, user *models.User, sessionID string, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNewConnection", ctx, user, sessionID, conn)
}

// AddNewConnection indicates an expected call of AddNewConnection.
func (mr *MockTableManagerMockRecorder) AddNewConnection(ctx, user, sessionID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewConnection", reflect.TypeOf((*MockTableManager)(nil).AddNewConnection), ctx, user, sessionID, conn)
}

// CreateSession mocks base method.
func (m *MockTableManager) CreateSession(ctx context.Context, admin *models.User, encounter *models.Encounter, sessionID string, callback func(string)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateSession", ctx, admin, encounter, sessionID, callback)
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockTableManagerMockRecorder) CreateSession(ctx, admin, encounter, sessionID, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockTableManager)(nil).CreateSession), ctx, admin, encounter, sessionID, callback)
}

// GetEncounterData mocks base method.
func (m *MockTableManager) GetEncounterData(ctx context.Context, sessionID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncounterData", ctx, sessionID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncounterData indicates an expected call of GetEncounterData.
func (mr *MockTableManagerMockRecorder) GetEncounterData(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncounterData", reflect.TypeOf((*MockTableManager)(nil).GetEncounterData), ctx, sessionID)
}

// GetTableData mocks base method.
func (m *MockTableManager) GetTableData(ctx context.Context, sessionID string) (*models.TableData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableData", ctx, sessionID)
	ret0, _ := ret[0].(*models.TableData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableData indicates an expected call of GetTableData.
func (mr *MockTableManagerMockRecorder) GetTableData(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableData", reflect.TypeOf((*MockTableManager)(nil).GetTableData), ctx, sessionID)
}

// HasActiveUsers mocks base method.
func (m *MockTableManager) HasActiveUsers(ctx context.Context, sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveUsers", ctx, sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveUsers indicates an expected call of HasActiveUsers.
func (mr *MockTableManagerMockRecorder) HasActiveUsers(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveUsers", reflect.TypeOf((*MockTableManager)(nil).HasActiveUsers), ctx, sessionID)
}

// RemoveSession mocks base method.
func (m *MockTableManager) RemoveSession(ctx context.Context, sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSession", ctx, sessionID)
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockTableManagerMockRecorder) RemoveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockTableManager)(nil).RemoveSession), ctx, sessionID)
}

// MockTableUsecases is a mock of TableUsecases interface.
type MockTableUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockTableUsecasesMockRecorder
	isgomock struct{}
}

// MockTableUsecasesMockRecorder is the mock recorder for MockTableUsecases.
type MockTableUsecasesMockRecorder struct {
	mock *MockTableUsecases
}

// NewMockTableUsecases creates a new mock instance.
func NewMockTableUsecases(ctrl *gomock.Controller) *MockTableUsecases {
	mock := &MockTableUsecases{ctrl: ctrl}
	mock.recorder = &MockTableUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableUsecases) EXPECT() *MockTableUsecasesMockRecorder {
	return m.recorder
}

// AddNewConnection mocks base method.
func (m *MockTableUsecases) AddNewConnection(ctx context.Context, user *models.User, sessionID string, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNewConnection", ctx, user, sessionID, conn)
}

// AddNewConnection indicates an expected call of AddNewConnection.
func (mr *MockTableUsecasesMockRecorder) AddNewConnection(ctx, user, sessionID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewConnection", reflect.TypeOf((*MockTableUsecases)(nil).AddNewConnection), ctx, user, sessionID, conn)
}

// CreateSession mocks base method.
func (m *MockTableUsecases) CreateSession(ctx context.Context, admin *models.User, encounterID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, admin, encounterID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockTableUsecasesMockRecorder) CreateSession(ctx, admin, encounterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockTableUsecases)(nil).CreateSession), ctx, admin, encounterID)
}

// GetTableData mocks base method.
func (m *MockTableUsecases) GetTableData(ctx context.Context, sessionID string) (*models.TableData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableData", ctx, sessionID)
	ret0, _ := ret[0].(*models.TableData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableData indicates an expected call of GetTableData.
func (mr *MockTableUsecasesMockRecorder) GetTableData(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableData", reflect.TypeOf((*MockTableUsecases)(nil).GetTableData), ctx, sessionID)
}

// MockSessionIDGenerator is a mock of SessionIDGenerator interface.
type MockSessionIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionIDGeneratorMockRecorder
	isgomock struct{}
}

// MockSessionIDGeneratorMockRecorder is the mock recorder for MockSessionIDGenerator.
type MockSessionIDGeneratorMockRecorder struct {
	mock *MockSessionIDGenerator
}

// NewMockSessionIDGenerator creates a new mock instance.
func NewMockSessionIDGenerator(ctrl *gomock.Controller) *MockSessionIDGenerator {
	mock := &MockSessionIDGenerator{ctrl: ctrl}
	mock.recorder = &MockSessionIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionIDGenerator) EXPECT() *MockSessionIDGeneratorMockRecorder {
	return m.recorder
}

// NewSessionID mocks base method.
func (m *MockSessionIDGenerator) NewSessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewSessionID indicates an expected call of NewSessionID.
func (mr *MockSessionIDGeneratorMockRecorder) NewSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSessionID", reflect.TypeOf((*MockSessionIDGenerator)(nil).NewSessionID))
}

// MockSessionTimer is a mock of SessionTimer interface.
type MockSessionTimer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionTimerMockRecorder
	isgomock struct{}
}

// MockSessionTimerMockRecorder is the mock recorder for MockSessionTimer.
type MockSessionTimerMockRecorder struct {
	mock *MockSessionTimer
}

// NewMockSessionTimer creates a new mock instance.
func NewMockSessionTimer(ctrl *gomock.Controller) *MockSessionTimer {
	mock := &MockSessionTimer{ctrl: ctrl}
	mock.recorder = &MockSessionTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionTimer) EXPECT() *MockSessionTimerMockRecorder {
	return m.recorder
}

// Reset mocks base method.
func (m *MockSessionTimer) Reset(d time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", d)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockSessionTimerMockRecorder) Reset(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockSessionTimer)(nil).Reset), d)
}

// Stop mocks base method.
func (m *MockSessionTimer) Stop() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSessionTimerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSessionTimer)(nil).Stop))
}

// MockTimerFactory is a mock of TimerFactory interface.
type MockTimerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTimerFactoryMockRecorder
	isgomock struct{}
}

// MockTimerFactoryMockRecorder is the mock recorder for MockTimerFactory.
type MockTimerFactoryMockRecorder struct {
	mock *MockTimerFactory
}

// NewMockTimerFactory creates a new mock instance.
func NewMockTimerFactory(ctrl *gomock.Controller) *MockTimerFactory {
	mock := &MockTimerFactory{ctrl: ctrl}
	mock.recorder = &MockTimerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimerFactory) EXPECT() *MockTimerFactoryMockRecorder {
	return m.recorder
}

// AfterFunc mocks base method.
func (m *MockTimerFactory) AfterFunc(d time.Duration, f func()) table.SessionTimer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterFunc", d, f)
	ret0, _ := ret[0].(table.SessionTimer)
	return ret0
}

// AfterFunc indicates an expected call of AfterFunc.
func (mr *MockTimerFactoryMockRecorder) AfterFunc(d, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterFunc", reflect.TypeOf((*MockTimerFactory)(nil).AfterFunc), d, f)
}
