// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthRepository) CreateUser(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthRepository)(nil).CreateUser), ctx, user)
}

// GetUserByID mocks base method.
func (m *MockAuthRepository) GetUserByID(ctx context.Context, userID int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthRepository)(nil).GetUserByID), ctx, userID)
}

// UpdateLastLoginAt mocks base method.
func (m *MockAuthRepository) UpdateLastLoginAt(ctx context.Context, userID int, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginAt", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginAt indicates an expected call of UpdateLastLoginAt.
func (mr *MockAuthRepositoryMockRecorder) UpdateLastLoginAt(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginAt", reflect.TypeOf((*MockAuthRepository)(nil).UpdateLastLoginAt), ctx, userID, t)
}

// UpdateUser mocks base method.
func (m *MockAuthRepository) UpdateUser(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAuthRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAuthRepository)(nil).UpdateUser), ctx, user)
}

// MockAuthUsecases is a mock of AuthUsecases interface.
type MockAuthUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecasesMockRecorder
	isgomock struct{}
}

// MockAuthUsecasesMockRecorder is the mock recorder for MockAuthUsecases.
type MockAuthUsecasesMockRecorder struct {
	mock *MockAuthUsecases
}

// NewMockAuthUsecases creates a new mock instance.
func NewMockAuthUsecases(ctrl *gomock.Controller) *MockAuthUsecases {
	mock := &MockAuthUsecases{ctrl: ctrl}
	mock.recorder = &MockAuthUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecases) EXPECT() *MockAuthUsecasesMockRecorder {
	return m.recorder
}

// CheckAuth mocks base method.
func (m *MockAuthUsecases) CheckAuth(ctx context.Context, sessionID string) (*models.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuth", ctx, sessionID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckAuth indicates an expected call of CheckAuth.
func (mr *MockAuthUsecasesMockRecorder) CheckAuth(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuth", reflect.TypeOf((*MockAuthUsecases)(nil).CheckAuth), ctx, sessionID)
}

// GetUserIDBySessionID mocks base method.
func (m *MockAuthUsecases) GetUserIDBySessionID(ctx context.Context, sessionID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetUserIDBySessionID indicates an expected call of GetUserIDBySessionID.
func (mr *MockAuthUsecasesMockRecorder) GetUserIDBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDBySessionID", reflect.TypeOf((*MockAuthUsecases)(nil).GetUserIDBySessionID), ctx, sessionID)
}

// Login mocks base method.
func (m *MockAuthUsecases) Login(ctx context.Context, provider, sessionID string, loginData *models.LoginRequest, sessionDuration time.Duration) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, provider, sessionID, loginData, sessionDuration)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthUsecasesMockRecorder) Login(ctx, provider, sessionID, loginData, sessionDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthUsecases)(nil).Login), ctx, provider, sessionID, loginData, sessionDuration)
}

// Logout mocks base method.
func (m *MockAuthUsecases) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthUsecasesMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthUsecases)(nil).Logout), ctx, sessionID)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionManager) CreateSession(ctx context.Context, sessionID string, session *models.FullSessionData, sessionDuration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, sessionID, session, sessionDuration)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionManagerMockRecorder) CreateSession(ctx, sessionID, session, sessionDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionManager)(nil).CreateSession), ctx, sessionID, session, sessionDuration)
}

// GetSession mocks base method.
func (m *MockSessionManager) GetSession(ctx context.Context, sessionID string) (*models.FullSessionData, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*models.FullSessionData)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionManagerMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionManager)(nil).GetSession), ctx, sessionID)
}

// RemoveSession mocks base method.
func (m *MockSessionManager) RemoveSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockSessionManagerMockRecorder) RemoveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockSessionManager)(nil).RemoveSession), ctx, sessionID)
}

// MockIdentityRepository is a mock of IdentityRepository interface.
type MockIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityRepositoryMockRecorder is the mock recorder for MockIdentityRepository.
type MockIdentityRepositoryMockRecorder struct {
	mock *MockIdentityRepository
}

// NewMockIdentityRepository creates a new mock instance.
func NewMockIdentityRepository(ctrl *gomock.Controller) *MockIdentityRepository {
	mock := &MockIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRepository) EXPECT() *MockIdentityRepositoryMockRecorder {
	return m.recorder
}

// CreateIdentity mocks base method.
func (m *MockIdentityRepository) CreateIdentity(ctx context.Context, identity *models.UserIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockIdentityRepositoryMockRecorder) CreateIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockIdentityRepository)(nil).CreateIdentity), ctx, identity)
}

// FindByProvider mocks base method.
func (m *MockIdentityRepository) FindByProvider(ctx context.Context, provider, providerUserID string) (*models.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProvider", ctx, provider, providerUserID)
	ret0, _ := ret[0].(*models.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProvider indicates an expected call of FindByProvider.
func (mr *MockIdentityRepositoryMockRecorder) FindByProvider(ctx, provider, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProvider", reflect.TypeOf((*MockIdentityRepository)(nil).FindByProvider), ctx, provider, providerUserID)
}

// ListByUserID mocks base method.
func (m *MockIdentityRepository) ListByUserID(ctx context.Context, userID int) ([]models.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockIdentityRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockIdentityRepository)(nil).ListByUserID), ctx, userID)
}

// UpdateLastUsed mocks base method.
func (m *MockIdentityRepository) UpdateLastUsed(ctx context.Context, identityID int, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, identityID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockIdentityRepositoryMockRecorder) UpdateLastUsed(ctx, identityID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockIdentityRepository)(nil).UpdateLastUsed), ctx, identityID, t)
}

// MockOAuthProvider is a mock of OAuthProvider interface.
type MockOAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthProviderMockRecorder
	isgomock struct{}
}

// MockOAuthProviderMockRecorder is the mock recorder for MockOAuthProvider.
type MockOAuthProviderMockRecorder struct {
	mock *MockOAuthProvider
}

// NewMockOAuthProvider creates a new mock instance.
func NewMockOAuthProvider(ctrl *gomock.Controller) *MockOAuthProvider {
	mock := &MockOAuthProvider{ctrl: ctrl}
	mock.recorder = &MockOAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthProvider) EXPECT() *MockOAuthProviderMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockOAuthProvider) Authenticate(ctx context.Context, loginData *models.LoginRequest) (*models.OAuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, loginData)
	ret0, _ := ret[0].(*models.OAuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockOAuthProviderMockRecorder) Authenticate(ctx, loginData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockOAuthProvider)(nil).Authenticate), ctx, loginData)
}

// Name mocks base method.
func (m *MockOAuthProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockOAuthProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockOAuthProvider)(nil).Name))
}
