// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_maps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMapsRepository is a mock of MapsRepository interface.
type MockMapsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMapsRepositoryMockRecorder
	isgomock struct{}
}

// MockMapsRepositoryMockRecorder is the mock recorder for MockMapsRepository.
type MockMapsRepositoryMockRecorder struct {
	mock *MockMapsRepository
}

// NewMockMapsRepository creates a new mock instance.
func NewMockMapsRepository(ctrl *gomock.Controller) *MockMapsRepository {
	mock := &MockMapsRepository{ctrl: ctrl}
	mock.recorder = &MockMapsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapsRepository) EXPECT() *MockMapsRepositoryMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockMapsRepository) CheckPermission(ctx context.Context, id string, userID int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, id, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockMapsRepositoryMockRecorder) CheckPermission(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockMapsRepository)(nil).CheckPermission), ctx, id, userID)
}

// CreateMap mocks base method.
func (m *MockMapsRepository) CreateMap(ctx context.Context, userID int, name string, data []byte) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMap", ctx, userID, name, data)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMap indicates an expected call of CreateMap.
func (mr *MockMapsRepositoryMockRecorder) CreateMap(ctx, userID, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMap", reflect.TypeOf((*MockMapsRepository)(nil).CreateMap), ctx, userID, name, data)
}

// DeleteMap mocks base method.
func (m *MockMapsRepository) DeleteMap(ctx context.Context, userID int, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMap", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMap indicates an expected call of DeleteMap.
func (mr *MockMapsRepositoryMockRecorder) DeleteMap(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMap", reflect.TypeOf((*MockMapsRepository)(nil).DeleteMap), ctx, userID, id)
}

// GetMapByID mocks base method.
func (m *MockMapsRepository) GetMapByID(ctx context.Context, userID int, id string) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapByID", ctx, userID, id)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapByID indicates an expected call of GetMapByID.
func (mr *MockMapsRepositoryMockRecorder) GetMapByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapByID", reflect.TypeOf((*MockMapsRepository)(nil).GetMapByID), ctx, userID, id)
}

// ListMaps mocks base method.
func (m *MockMapsRepository) ListMaps(ctx context.Context, userID, start, size int) (*models.MapsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaps", ctx, userID, start, size)
	ret0, _ := ret[0].(*models.MapsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaps indicates an expected call of ListMaps.
func (mr *MockMapsRepositoryMockRecorder) ListMaps(ctx, userID, start, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaps", reflect.TypeOf((*MockMapsRepository)(nil).ListMaps), ctx, userID, start, size)
}

// UpdateMap mocks base method.
func (m *MockMapsRepository) UpdateMap(ctx context.Context, userID int, id, name string, data []byte) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMap", ctx, userID, id, name, data)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMap indicates an expected call of UpdateMap.
func (mr *MockMapsRepositoryMockRecorder) UpdateMap(ctx, userID, id, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMap", reflect.TypeOf((*MockMapsRepository)(nil).UpdateMap), ctx, userID, id, name, data)
}

// MockMapsUsecases is a mock of MapsUsecases interface.
type MockMapsUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockMapsUsecasesMockRecorder
	isgomock struct{}
}

// MockMapsUsecasesMockRecorder is the mock recorder for MockMapsUsecases.
type MockMapsUsecasesMockRecorder struct {
	mock *MockMapsUsecases
}

// NewMockMapsUsecases creates a new mock instance.
func NewMockMapsUsecases(ctrl *gomock.Controller) *MockMapsUsecases {
	mock := &MockMapsUsecases{ctrl: ctrl}
	mock.recorder = &MockMapsUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapsUsecases) EXPECT() *MockMapsUsecasesMockRecorder {
	return m.recorder
}

// CreateMap mocks base method.
func (m *MockMapsUsecases) CreateMap(ctx context.Context, userID int, req *models.CreateMapRequest) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMap", ctx, userID, req)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMap indicates an expected call of CreateMap.
func (mr *MockMapsUsecasesMockRecorder) CreateMap(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMap", reflect.TypeOf((*MockMapsUsecases)(nil).CreateMap), ctx, userID, req)
}

// DeleteMap mocks base method.
func (m *MockMapsUsecases) DeleteMap(ctx context.Context, userID int, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMap", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMap indicates an expected call of DeleteMap.
func (mr *MockMapsUsecasesMockRecorder) DeleteMap(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMap", reflect.TypeOf((*MockMapsUsecases)(nil).DeleteMap), ctx, userID, id)
}

// GetMapByID mocks base method.
func (m *MockMapsUsecases) GetMapByID(ctx context.Context, userID int, id string) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapByID", ctx, userID, id)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapByID indicates an expected call of GetMapByID.
func (mr *MockMapsUsecasesMockRecorder) GetMapByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapByID", reflect.TypeOf((*MockMapsUsecases)(nil).GetMapByID), ctx, userID, id)
}

// ListMaps mocks base method.
func (m *MockMapsUsecases) ListMaps(ctx context.Context, userID, start, size int) (*models.MapsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaps", ctx, userID, start, size)
	ret0, _ := ret[0].(*models.MapsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaps indicates an expected call of ListMaps.
func (mr *MockMapsUsecasesMockRecorder) ListMaps(ctx, userID, start, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaps", reflect.TypeOf((*MockMapsUsecases)(nil).ListMaps), ctx, userID, start, size)
}

// UpdateMap mocks base method.
func (m *MockMapsUsecases) UpdateMap(ctx context.Context, userID int, id string, req *models.UpdateMapRequest) (*models.MapFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMap", ctx, userID, id, req)
	ret0, _ := ret[0].(*models.MapFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMap indicates an expected call of UpdateMap.
func (mr *MockMapsUsecasesMockRecorder) UpdateMap(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMap", reflect.TypeOf((*MockMapsUsecases)(nil).UpdateMap), ctx, userID, id, req)
}
