// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_encounter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEncounterRepository is a mock of EncounterRepository interface.
type MockEncounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEncounterRepositoryMockRecorder
	isgomock struct{}
}

// MockEncounterRepositoryMockRecorder is the mock recorder for MockEncounterRepository.
type MockEncounterRepositoryMockRecorder struct {
	mock *MockEncounterRepository
}

// NewMockEncounterRepository creates a new mock instance.
func NewMockEncounterRepository(ctrl *gomock.Controller) *MockEncounterRepository {
	mock := &MockEncounterRepository{ctrl: ctrl}
	mock.recorder = &MockEncounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncounterRepository) EXPECT() *MockEncounterRepositoryMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockEncounterRepository) CheckPermission(ctx context.Context, id string, userID int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, id, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockEncounterRepositoryMockRecorder) CheckPermission(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockEncounterRepository)(nil).CheckPermission), ctx, id, userID)
}

// GetEncounterByID mocks base method.
func (m *MockEncounterRepository) GetEncounterByID(ctx context.Context, id string) (*models.Encounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncounterByID", ctx, id)
	ret0, _ := ret[0].(*models.Encounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncounterByID indicates an expected call of GetEncounterByID.
func (mr *MockEncounterRepositoryMockRecorder) GetEncounterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncounterByID", reflect.TypeOf((*MockEncounterRepository)(nil).GetEncounterByID), ctx, id)
}

// GetEncountersList mocks base method.
func (m *MockEncounterRepository) GetEncountersList(ctx context.Context, size, start, userID int) (*models.EncountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncountersList", ctx, size, start, userID)
	ret0, _ := ret[0].(*models.EncountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncountersList indicates an expected call of GetEncountersList.
func (mr *MockEncounterRepositoryMockRecorder) GetEncountersList(ctx, size, start, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncountersList", reflect.TypeOf((*MockEncounterRepository)(nil).GetEncountersList), ctx, size, start, userID)
}

// GetEncountersListWithSearch mocks base method.
func (m *MockEncounterRepository) GetEncountersListWithSearch(ctx context.Context, size, start, userID int, search *models.SearchParams) (*models.EncountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncountersListWithSearch", ctx, size, start, userID, search)
	ret0, _ := ret[0].(*models.EncountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncountersListWithSearch indicates an expected call of GetEncountersListWithSearch.
func (mr *MockEncounterRepositoryMockRecorder) GetEncountersListWithSearch(ctx, size, start, userID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncountersListWithSearch", reflect.TypeOf((*MockEncounterRepository)(nil).GetEncountersListWithSearch), ctx, size, start, userID, search)
}

// RemoveEncounter mocks base method.
func (m *MockEncounterRepository) RemoveEncounter(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEncounter", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEncounter indicates an expected call of RemoveEncounter.
func (mr *MockEncounterRepositoryMockRecorder) RemoveEncounter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEncounter", reflect.TypeOf((*MockEncounterRepository)(nil).RemoveEncounter), ctx, id)
}

// SaveEncounter mocks base method.
func (m *MockEncounterRepository) SaveEncounter(ctx context.Context, encounter *models.SaveEncounterReq, id string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEncounter", ctx, encounter, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEncounter indicates an expected call of SaveEncounter.
func (mr *MockEncounterRepositoryMockRecorder) SaveEncounter(ctx, encounter, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEncounter", reflect.TypeOf((*MockEncounterRepository)(nil).SaveEncounter), ctx, encounter, id, userID)
}

// UpdateEncounter mocks base method.
func (m *MockEncounterRepository) UpdateEncounter(ctx context.Context, data []byte, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncounter", ctx, data, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEncounter indicates an expected call of UpdateEncounter.
func (mr *MockEncounterRepositoryMockRecorder) UpdateEncounter(ctx, data, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncounter", reflect.TypeOf((*MockEncounterRepository)(nil).UpdateEncounter), ctx, data, id)
}

// MockEncounterUsecases is a mock of EncounterUsecases interface.
type MockEncounterUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockEncounterUsecasesMockRecorder
	isgomock struct{}
}

// MockEncounterUsecasesMockRecorder is the mock recorder for MockEncounterUsecases.
type MockEncounterUsecasesMockRecorder struct {
	mock *MockEncounterUsecases
}

// NewMockEncounterUsecases creates a new mock instance.
func NewMockEncounterUsecases(ctrl *gomock.Controller) *MockEncounterUsecases {
	mock := &MockEncounterUsecases{ctrl: ctrl}
	mock.recorder = &MockEncounterUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncounterUsecases) EXPECT() *MockEncounterUsecasesMockRecorder {
	return m.recorder
}

// GetEncounterByID mocks base method.
func (m *MockEncounterUsecases) GetEncounterByID(ctx context.Context, id string, userID int) (*models.Encounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncounterByID", ctx, id, userID)
	ret0, _ := ret[0].(*models.Encounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncounterByID indicates an expected call of GetEncounterByID.
func (mr *MockEncounterUsecasesMockRecorder) GetEncounterByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncounterByID", reflect.TypeOf((*MockEncounterUsecases)(nil).GetEncounterByID), ctx, id, userID)
}

// GetEncountersList mocks base method.
func (m *MockEncounterUsecases) GetEncountersList(ctx context.Context, size, start, userID int, search *models.SearchParams) (*models.EncountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncountersList", ctx, size, start, userID, search)
	ret0, _ := ret[0].(*models.EncountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncountersList indicates an expected call of GetEncountersList.
func (mr *MockEncounterUsecasesMockRecorder) GetEncountersList(ctx, size, start, userID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncountersList", reflect.TypeOf((*MockEncounterUsecases)(nil).GetEncountersList), ctx, size, start, userID, search)
}

// RemoveEncounter mocks base method.
func (m *MockEncounterUsecases) RemoveEncounter(ctx context.Context, id string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEncounter", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEncounter indicates an expected call of RemoveEncounter.
func (mr *MockEncounterUsecasesMockRecorder) RemoveEncounter(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEncounter", reflect.TypeOf((*MockEncounterUsecases)(nil).RemoveEncounter), ctx, id, userID)
}

// SaveEncounter mocks base method.
func (m *MockEncounterUsecases) SaveEncounter(ctx context.Context, encounter *models.SaveEncounterReq, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEncounter", ctx, encounter, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEncounter indicates an expected call of SaveEncounter.
func (mr *MockEncounterUsecasesMockRecorder) SaveEncounter(ctx, encounter, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEncounter", reflect.TypeOf((*MockEncounterUsecases)(nil).SaveEncounter), ctx, encounter, userID)
}

// UpdateEncounter mocks base method.
func (m *MockEncounterUsecases) UpdateEncounter(ctx context.Context, data []byte, id string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncounter", ctx, data, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEncounter indicates an expected call of UpdateEncounter.
func (mr *MockEncounterUsecasesMockRecorder) UpdateEncounter(ctx, data, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncounter", reflect.TypeOf((*MockEncounterUsecases)(nil).UpdateEncounter), ctx, data, id, userID)
}
