// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_bestiary.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/IlyaChgn/2025_IMAO_DnD_Assistant_backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBestiaryRepository is a mock of BestiaryRepository interface.
type MockBestiaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBestiaryRepositoryMockRecorder
	isgomock struct{}
}

// MockBestiaryRepositoryMockRecorder is the mock recorder for MockBestiaryRepository.
type MockBestiaryRepositoryMockRecorder struct {
	mock *MockBestiaryRepository
}

// NewMockBestiaryRepository creates a new mock instance.
func NewMockBestiaryRepository(ctrl *gomock.Controller) *MockBestiaryRepository {
	mock := &MockBestiaryRepository{ctrl: ctrl}
	mock.recorder = &MockBestiaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBestiaryRepository) EXPECT() *MockBestiaryRepositoryMockRecorder {
	return m.recorder
}

// AddGeneratedCreature mocks base method.
func (m *MockBestiaryRepository) AddGeneratedCreature(ctx context.Context, generatedCreature models.Creature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGeneratedCreature", ctx, generatedCreature)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGeneratedCreature indicates an expected call of AddGeneratedCreature.
func (mr *MockBestiaryRepositoryMockRecorder) AddGeneratedCreature(ctx, generatedCreature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGeneratedCreature", reflect.TypeOf((*MockBestiaryRepository)(nil).AddGeneratedCreature), ctx, generatedCreature)
}

// GetCreatureByEngName mocks base method.
func (m *MockBestiaryRepository) GetCreatureByEngName(ctx context.Context, engName string, isUserCollection bool) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatureByEngName", ctx, engName, isUserCollection)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatureByEngName indicates an expected call of GetCreatureByEngName.
func (mr *MockBestiaryRepositoryMockRecorder) GetCreatureByEngName(ctx, engName, isUserCollection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatureByEngName", reflect.TypeOf((*MockBestiaryRepository)(nil).GetCreatureByEngName), ctx, engName, isUserCollection)
}

// GetCreaturesList mocks base method.
func (m *MockBestiaryRepository) GetCreaturesList(ctx context.Context, size, start int, order []models.Order, filter models.FilterParams, search models.SearchParams) ([]*models.BestiaryCreature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreaturesList", ctx, size, start, order, filter, search)
	ret0, _ := ret[0].([]*models.BestiaryCreature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreaturesList indicates an expected call of GetCreaturesList.
func (mr *MockBestiaryRepositoryMockRecorder) GetCreaturesList(ctx, size, start, order, filter, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreaturesList", reflect.TypeOf((*MockBestiaryRepository)(nil).GetCreaturesList), ctx, size, start, order, filter, search)
}

// GetUserCreaturesList mocks base method.
func (m *MockBestiaryRepository) GetUserCreaturesList(ctx context.Context, size, start int, order []models.Order, filter models.FilterParams, search models.SearchParams, userID int) ([]*models.BestiaryCreature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCreaturesList", ctx, size, start, order, filter, search, userID)
	ret0, _ := ret[0].([]*models.BestiaryCreature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCreaturesList indicates an expected call of GetUserCreaturesList.
func (mr *MockBestiaryRepositoryMockRecorder) GetUserCreaturesList(ctx, size, start, order, filter, search, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCreaturesList", reflect.TypeOf((*MockBestiaryRepository)(nil).GetUserCreaturesList), ctx, size, start, order, filter, search, userID)
}

// MockBestiaryUsecases is a mock of BestiaryUsecases interface.
type MockBestiaryUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockBestiaryUsecasesMockRecorder
	isgomock struct{}
}

// MockBestiaryUsecasesMockRecorder is the mock recorder for MockBestiaryUsecases.
type MockBestiaryUsecasesMockRecorder struct {
	mock *MockBestiaryUsecases
}

// NewMockBestiaryUsecases creates a new mock instance.
func NewMockBestiaryUsecases(ctrl *gomock.Controller) *MockBestiaryUsecases {
	mock := &MockBestiaryUsecases{ctrl: ctrl}
	mock.recorder = &MockBestiaryUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBestiaryUsecases) EXPECT() *MockBestiaryUsecasesMockRecorder {
	return m.recorder
}

// AddGeneratedCreature mocks base method.
func (m *MockBestiaryUsecases) AddGeneratedCreature(ctx context.Context, creatureInput models.CreatureInput, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGeneratedCreature", ctx, creatureInput, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGeneratedCreature indicates an expected call of AddGeneratedCreature.
func (mr *MockBestiaryUsecasesMockRecorder) AddGeneratedCreature(ctx, creatureInput, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGeneratedCreature", reflect.TypeOf((*MockBestiaryUsecases)(nil).AddGeneratedCreature), ctx, creatureInput, userID)
}

// GenerateCreatureFromDescription mocks base method.
func (m *MockBestiaryUsecases) GenerateCreatureFromDescription(ctx context.Context, description string) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCreatureFromDescription", ctx, description)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCreatureFromDescription indicates an expected call of GenerateCreatureFromDescription.
func (mr *MockBestiaryUsecasesMockRecorder) GenerateCreatureFromDescription(ctx, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCreatureFromDescription", reflect.TypeOf((*MockBestiaryUsecases)(nil).GenerateCreatureFromDescription), ctx, description)
}

// GetCreatureByEngName mocks base method.
func (m *MockBestiaryUsecases) GetCreatureByEngName(ctx context.Context, engName string) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatureByEngName", ctx, engName)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatureByEngName indicates an expected call of GetCreatureByEngName.
func (mr *MockBestiaryUsecasesMockRecorder) GetCreatureByEngName(ctx, engName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatureByEngName", reflect.TypeOf((*MockBestiaryUsecases)(nil).GetCreatureByEngName), ctx, engName)
}

// GetCreaturesList mocks base method.
func (m *MockBestiaryUsecases) GetCreaturesList(ctx context.Context, size, start int, order []models.Order, filter models.FilterParams, search models.SearchParams) ([]*models.BestiaryCreature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreaturesList", ctx, size, start, order, filter, search)
	ret0, _ := ret[0].([]*models.BestiaryCreature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreaturesList indicates an expected call of GetCreaturesList.
func (mr *MockBestiaryUsecasesMockRecorder) GetCreaturesList(ctx, size, start, order, filter, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreaturesList", reflect.TypeOf((*MockBestiaryUsecases)(nil).GetCreaturesList), ctx, size, start, order, filter, search)
}

// GetUserCreatureByEngName mocks base method.
func (m *MockBestiaryUsecases) GetUserCreatureByEngName(ctx context.Context, engName string, userID int) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCreatureByEngName", ctx, engName, userID)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCreatureByEngName indicates an expected call of GetUserCreatureByEngName.
func (mr *MockBestiaryUsecasesMockRecorder) GetUserCreatureByEngName(ctx, engName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCreatureByEngName", reflect.TypeOf((*MockBestiaryUsecases)(nil).GetUserCreatureByEngName), ctx, engName, userID)
}

// GetUserCreaturesList mocks base method.
func (m *MockBestiaryUsecases) GetUserCreaturesList(ctx context.Context, size, start int, order []models.Order, filter models.FilterParams, search models.SearchParams, userID int) ([]*models.BestiaryCreature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCreaturesList", ctx, size, start, order, filter, search, userID)
	ret0, _ := ret[0].([]*models.BestiaryCreature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCreaturesList indicates an expected call of GetUserCreaturesList.
func (mr *MockBestiaryUsecasesMockRecorder) GetUserCreaturesList(ctx, size, start, order, filter, search, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCreaturesList", reflect.TypeOf((*MockBestiaryUsecases)(nil).GetUserCreaturesList), ctx, size, start, order, filter, search, userID)
}

// ParseCreatureFromImage mocks base method.
func (m *MockBestiaryUsecases) ParseCreatureFromImage(ctx context.Context, image []byte) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseCreatureFromImage", ctx, image)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseCreatureFromImage indicates an expected call of ParseCreatureFromImage.
func (mr *MockBestiaryUsecasesMockRecorder) ParseCreatureFromImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseCreatureFromImage", reflect.TypeOf((*MockBestiaryUsecases)(nil).ParseCreatureFromImage), ctx, image)
}

// MockBestiaryS3Manager is a mock of BestiaryS3Manager interface.
type MockBestiaryS3Manager struct {
	ctrl     *gomock.Controller
	recorder *MockBestiaryS3ManagerMockRecorder
	isgomock struct{}
}

// MockBestiaryS3ManagerMockRecorder is the mock recorder for MockBestiaryS3Manager.
type MockBestiaryS3ManagerMockRecorder struct {
	mock *MockBestiaryS3Manager
}

// NewMockBestiaryS3Manager creates a new mock instance.
func NewMockBestiaryS3Manager(ctrl *gomock.Controller) *MockBestiaryS3Manager {
	mock := &MockBestiaryS3Manager{ctrl: ctrl}
	mock.recorder = &MockBestiaryS3ManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBestiaryS3Manager) EXPECT() *MockBestiaryS3ManagerMockRecorder {
	return m.recorder
}

// UploadImage mocks base method.
func (m *MockBestiaryS3Manager) UploadImage(ctx context.Context, base64Data, objectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, base64Data, objectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockBestiaryS3ManagerMockRecorder) UploadImage(ctx, base64Data, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockBestiaryS3Manager)(nil).UploadImage), ctx, base64Data, objectName)
}

// MockGeminiAPI is a mock of GeminiAPI interface.
type MockGeminiAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiAPIMockRecorder
	isgomock struct{}
}

// MockGeminiAPIMockRecorder is the mock recorder for MockGeminiAPI.
type MockGeminiAPIMockRecorder struct {
	mock *MockGeminiAPI
}

// NewMockGeminiAPI creates a new mock instance.
func NewMockGeminiAPI(ctrl *gomock.Controller) *MockGeminiAPI {
	mock := &MockGeminiAPI{ctrl: ctrl}
	mock.recorder = &MockGeminiAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiAPI) EXPECT() *MockGeminiAPIMockRecorder {
	return m.recorder
}

// GenerateFromDescription mocks base method.
func (m *MockGeminiAPI) GenerateFromDescription(ctx context.Context, desc string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFromDescription", ctx, desc)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateFromDescription indicates an expected call of GenerateFromDescription.
func (mr *MockGeminiAPIMockRecorder) GenerateFromDescription(ctx, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFromDescription", reflect.TypeOf((*MockGeminiAPI)(nil).GenerateFromDescription), ctx, desc)
}

// GenerateFromImage mocks base method.
func (m *MockGeminiAPI) GenerateFromImage(ctx context.Context, image []byte) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFromImage", ctx, image)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateFromImage indicates an expected call of GenerateFromImage.
func (mr *MockGeminiAPIMockRecorder) GenerateFromImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFromImage", reflect.TypeOf((*MockGeminiAPI)(nil).GenerateFromImage), ctx, image)
}

// MockLLMJobRepository is a mock of LLMJobRepository interface.
type MockLLMJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMJobRepositoryMockRecorder
	isgomock struct{}
}

// MockLLMJobRepositoryMockRecorder is the mock recorder for MockLLMJobRepository.
type MockLLMJobRepositoryMockRecorder struct {
	mock *MockLLMJobRepository
}

// NewMockLLMJobRepository creates a new mock instance.
func NewMockLLMJobRepository(ctrl *gomock.Controller) *MockLLMJobRepository {
	mock := &MockLLMJobRepository{ctrl: ctrl}
	mock.recorder = &MockLLMJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMJobRepository) EXPECT() *MockLLMJobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLLMJobRepository) Create(ctx context.Context, job *models.LLMJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLLMJobRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLLMJobRepository)(nil).Create), ctx, job)
}

// Get mocks base method.
func (m *MockLLMJobRepository) Get(ctx context.Context, id string) (*models.LLMJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.LLMJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLLMJobRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLLMJobRepository)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockLLMJobRepository) Update(ctx context.Context, job *models.LLMJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLLMJobRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLLMJobRepository)(nil).Update), ctx, job)
}

// MockGenerationUsecases is a mock of GenerationUsecases interface.
type MockGenerationUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationUsecasesMockRecorder
	isgomock struct{}
}

// MockGenerationUsecasesMockRecorder is the mock recorder for MockGenerationUsecases.
type MockGenerationUsecasesMockRecorder struct {
	mock *MockGenerationUsecases
}

// NewMockGenerationUsecases creates a new mock instance.
func NewMockGenerationUsecases(ctrl *gomock.Controller) *MockGenerationUsecases {
	mock := &MockGenerationUsecases{ctrl: ctrl}
	mock.recorder = &MockGenerationUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationUsecases) EXPECT() *MockGenerationUsecasesMockRecorder {
	return m.recorder
}

// GetJob mocks base method.
func (m *MockGenerationUsecases) GetJob(ctx context.Context, id string) (*models.LLMJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, id)
	ret0, _ := ret[0].(*models.LLMJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockGenerationUsecasesMockRecorder) GetJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockGenerationUsecases)(nil).GetJob), ctx, id)
}

// SubmitImage mocks base method.
func (m *MockGenerationUsecases) SubmitImage(ctx context.Context, img []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitImage", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitImage indicates an expected call of SubmitImage.
func (mr *MockGenerationUsecasesMockRecorder) SubmitImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitImage", reflect.TypeOf((*MockGenerationUsecases)(nil).SubmitImage), ctx, img)
}

// SubmitText mocks base method.
func (m *MockGenerationUsecases) SubmitText(ctx context.Context, desc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitText", ctx, desc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitText indicates an expected call of SubmitText.
func (mr *MockGenerationUsecasesMockRecorder) SubmitText(ctx, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitText", reflect.TypeOf((*MockGenerationUsecases)(nil).SubmitText), ctx, desc)
}

// MockGeneratedCreatureProcessorUsecases is a mock of GeneratedCreatureProcessorUsecases interface.
type MockGeneratedCreatureProcessorUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratedCreatureProcessorUsecasesMockRecorder
	isgomock struct{}
}

// MockGeneratedCreatureProcessorUsecasesMockRecorder is the mock recorder for MockGeneratedCreatureProcessorUsecases.
type MockGeneratedCreatureProcessorUsecasesMockRecorder struct {
	mock *MockGeneratedCreatureProcessorUsecases
}

// NewMockGeneratedCreatureProcessorUsecases creates a new mock instance.
func NewMockGeneratedCreatureProcessorUsecases(ctrl *gomock.Controller) *MockGeneratedCreatureProcessorUsecases {
	mock := &MockGeneratedCreatureProcessorUsecases{ctrl: ctrl}
	mock.recorder = &MockGeneratedCreatureProcessorUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratedCreatureProcessorUsecases) EXPECT() *MockGeneratedCreatureProcessorUsecasesMockRecorder {
	return m.recorder
}

// ValidateAndProcessGeneratedCreature mocks base method.
func (m *MockGeneratedCreatureProcessorUsecases) ValidateAndProcessGeneratedCreature(ctx context.Context, c *models.Creature) (*models.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndProcessGeneratedCreature", ctx, c)
	ret0, _ := ret[0].(*models.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndProcessGeneratedCreature indicates an expected call of ValidateAndProcessGeneratedCreature.
func (mr *MockGeneratedCreatureProcessorUsecasesMockRecorder) ValidateAndProcessGeneratedCreature(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndProcessGeneratedCreature", reflect.TypeOf((*MockGeneratedCreatureProcessorUsecases)(nil).ValidateAndProcessGeneratedCreature), ctx, c)
}

// MockActionProcessorUsecases is a mock of ActionProcessorUsecases interface.
type MockActionProcessorUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockActionProcessorUsecasesMockRecorder
	isgomock struct{}
}

// MockActionProcessorUsecasesMockRecorder is the mock recorder for MockActionProcessorUsecases.
type MockActionProcessorUsecasesMockRecorder struct {
	mock *MockActionProcessorUsecases
}

// NewMockActionProcessorUsecases creates a new mock instance.
func NewMockActionProcessorUsecases(ctrl *gomock.Controller) *MockActionProcessorUsecases {
	mock := &MockActionProcessorUsecases{ctrl: ctrl}
	mock.recorder = &MockActionProcessorUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionProcessorUsecases) EXPECT() *MockActionProcessorUsecasesMockRecorder {
	return m.recorder
}

// ProcessActions mocks base method.
func (m *MockActionProcessorUsecases) ProcessActions(ctx context.Context, actions []models.Action) ([]models.AttackLLM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessActions", ctx, actions)
	ret0, _ := ret[0].([]models.AttackLLM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessActions indicates an expected call of ProcessActions.
func (mr *MockActionProcessorUsecasesMockRecorder) ProcessActions(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessActions", reflect.TypeOf((*MockActionProcessorUsecases)(nil).ProcessActions), ctx, actions)
}

// MockActionProcessorGateway is a mock of ActionProcessorGateway interface.
type MockActionProcessorGateway struct {
	ctrl     *gomock.Controller
	recorder *MockActionProcessorGatewayMockRecorder
	isgomock struct{}
}

// MockActionProcessorGatewayMockRecorder is the mock recorder for MockActionProcessorGateway.
type MockActionProcessorGatewayMockRecorder struct {
	mock *MockActionProcessorGateway
}

// NewMockActionProcessorGateway creates a new mock instance.
func NewMockActionProcessorGateway(ctrl *gomock.Controller) *MockActionProcessorGateway {
	mock := &MockActionProcessorGateway{ctrl: ctrl}
	mock.recorder = &MockActionProcessorGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionProcessorGateway) EXPECT() *MockActionProcessorGatewayMockRecorder {
	return m.recorder
}

// ProcessActions mocks base method.
func (m *MockActionProcessorGateway) ProcessActions(ctx context.Context, actions []models.Action) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessActions", ctx, actions)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessActions indicates an expected call of ProcessActions.
func (mr *MockActionProcessorGatewayMockRecorder) ProcessActions(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessActions", reflect.TypeOf((*MockActionProcessorGateway)(nil).ProcessActions), ctx, actions)
}

// MockAsyncRunner is a mock of AsyncRunner interface.
type MockAsyncRunner struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncRunnerMockRecorder
	isgomock struct{}
}

// MockAsyncRunnerMockRecorder is the mock recorder for MockAsyncRunner.
type MockAsyncRunnerMockRecorder struct {
	mock *MockAsyncRunner
}

// NewMockAsyncRunner creates a new mock instance.
func NewMockAsyncRunner(ctrl *gomock.Controller) *MockAsyncRunner {
	mock := &MockAsyncRunner{ctrl: ctrl}
	mock.recorder = &MockAsyncRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncRunner) EXPECT() *MockAsyncRunnerMockRecorder {
	return m.recorder
}

// Go mocks base method.
func (m *MockAsyncRunner) Go(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Go", fn)
}

// Go indicates an expected call of Go.
func (mr *MockAsyncRunnerMockRecorder) Go(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockAsyncRunner)(nil).Go), fn)
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDGenerator) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDGeneratorMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDGenerator)(nil).NewID))
}
